name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

# Versiyonu 1.0.1+5 yaptık çünkü Apple aynı versiyonu tekrar kabul etmez.
version: 1.0.2+110

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # İkon paketi buraya ekleniyor
  flutter_launcher_icons: ^0.13.1

# İkon konfigürasyonu
flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icon/app_icon.jpg"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  # Assets kısmına ikon klasörünü tanıtıyoruz
  assets:
    - assets/icon/app_icon.jpg